name: publish

on:
  push:
    tags:
      - "v*"

jobs:
  pack-and-publish:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Extract version from tag
        id: get_version
        shell: bash
        run: |
          ref="${GITHUB_REF##*/}"
          echo "ref=$ref"
          ver="${ref#v}"
          echo "version=$ver"
          echo "version=$ver" >> $GITHUB_OUTPUT

      - name: Restore
        run: dotnet restore jaywapp/Jaywapp.Infrastructure/Jaywapp.Infrastructure.csproj

      - name: Pack
        run: dotnet pack jaywapp/Jaywapp.Infrastructure/Jaywapp.Infrastructure.csproj -c Release -o nupkg /p:Version=${{ steps.get_version.outputs.version }}

      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push "nupkg/*.nupkg" --api-key "$env:NUGET_API_KEY" --source https://api.nuget.org/v3/index.json --skip-duplicate

